import Header from "@/components/Header";
import LocalStorageCartProvider from "@/services/CartProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LocalStorageCartProvider>
          <Header />
          {children}
        </LocalStorageCartProvider>
      </body>
    </html>
  );
}
